CREATE TABLE IF NOT EXISTS MatHang (
    MaHang INTEGER PRIMARY KEY AUTOINCREMENT,
    TenHang TEXT UNIQUE NOT NULL,
    DonViTinh TEXT,
    LoaiHang TEXT,
    MoTa TEXT,
    TonToiThieu INTEGER DEFAULT 0,
    TrangThai TEXT,
    NgayTao TEXT DEFAULT (datetime('now')), 
    IsDeleted INTEGER DEFAULT 0
);


CREATE TABLE IF NOT EXISTS NhapKho (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    MaHang INTEGER NOT NULL,
    SoLuong INTEGER NOT NULL,
    GiaNhap REAL NOT NULL,
    FOREIGN KEY (MaHang) REFERENCES MatHang(MaHang)
);


-- ALTER TABLE NhapKho ADD COLUMN NhaCungCap TEXT;      
-- ALTER TABLE NhapKho ADD COLUMN NhanVienNhap TEXT;    
-- ALTER TABLE NhapKho ADD COLUMN HanSuDung TEXT;       
-- ALTER TABLE NhapKho ADD COLUMN SoHoaDon TEXT;        
-- ALTER TABLE NhapKho ADD COLUMN GhiChu TEXT;          
-- ALTER TABLE NhapKho ADD COLUMN NgayTao TEXT DEFAULT (datetime('now'));  
-- ALTER TABLE NhapKho ADD COLUMN IsDeleted INTEGER DEFAULT 0;  
